[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "daytona_sdk"
version = "0.1.3"
authors = [
    { name = "Vedran Jukic", email = "vedran.jukic@gmail.com" },
]
description = "Python SDK for Daytona"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "environs>=9.5.0,<10.0.0",
    "marshmallow>=3.19.0,<4.0.0",
    "pydantic>=2.4.2,<3.0.0",
    "python-dateutil>=2.8.2,<3.0.0",
    "urllib3>=2.0.7,<3.0.0"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
keywords = ["daytona", "sdk"]
license = {text = "Apache 2.0"}