# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_sdk.api.api_key_api import ApiKeyApi


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyApi()

    def tearDown(self) -> None:
        pass

    def test_generate_api_key(self) -> None:
        """Test case for generate_api_key

        Generate an API key
        """
        pass

    def test_list_client_api_keys(self) -> None:
        """Test case for list_client_api_keys

        List API keys
        """
        pass

    def test_revoke_api_key(self) -> None:
        """Test case for revoke_api_key

        Revoke API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
