# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_sdk.api.workspace_api import WorkspaceApi


class TestWorkspaceApi(unittest.TestCase):
    """WorkspaceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceApi()

    def tearDown(self) -> None:
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create a workspace
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Get workspace info
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        List workspaces
        """
        pass

    def test_remove_workspace(self) -> None:
        """Test case for remove_workspace

        Remove workspace
        """
        pass

    def test_set_project_state(self) -> None:
        """Test case for set_project_state

        Set project state
        """
        pass

    def test_start_project(self) -> None:
        """Test case for start_project

        Start project
        """
        pass

    def test_start_workspace(self) -> None:
        """Test case for start_workspace

        Start workspace
        """
        pass

    def test_stop_project(self) -> None:
        """Test case for stop_project

        Stop project
        """
        pass

    def test_stop_workspace(self) -> None:
        """Test case for stop_workspace

        Stop workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
