# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_sdk.api.profile_api import ProfileApi


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfileApi()

    def tearDown(self) -> None:
        pass

    def test_delete_profile_data(self) -> None:
        """Test case for delete_profile_data

        Delete profile data
        """
        pass

    def test_get_profile_data(self) -> None:
        """Test case for get_profile_data

        Get profile data
        """
        pass

    def test_set_profile_data(self) -> None:
        """Test case for set_profile_data

        Set profile data
        """
        pass


if __name__ == '__main__':
    unittest.main()
