# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona.gclient.daytona_sdk.models.apikey_api_key_type import ApikeyApiKeyType

class TestApikeyApiKeyType(unittest.TestCase):
    """ApikeyApiKeyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApikeyApiKeyType(self):
        """Test ApikeyApiKeyType"""
        # inst = ApikeyApiKeyType()

if __name__ == '__main__':
    unittest.main()
