# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona.gclient.daytona_sdk.api.workspace_toolbox_api import WorkspaceToolboxApi


class TestWorkspaceToolboxApi(unittest.TestCase):
    """WorkspaceToolboxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceToolboxApi()

    def tearDown(self) -> None:
        pass

    def test_fs_create_folder(self) -> None:
        """Test case for fs_create_folder

        Create folder
        """
        pass

    def test_fs_delete_file(self) -> None:
        """Test case for fs_delete_file

        Delete file
        """
        pass

    def test_fs_download_file(self) -> None:
        """Test case for fs_download_file

        Download file
        """
        pass

    def test_fs_find_in_files(self) -> None:
        """Test case for fs_find_in_files

        Search for text/pattern in files
        """
        pass

    def test_fs_get_file_details(self) -> None:
        """Test case for fs_get_file_details

        Get file info
        """
        pass

    def test_fs_list_files(self) -> None:
        """Test case for fs_list_files

        List files
        """
        pass

    def test_fs_move_file(self) -> None:
        """Test case for fs_move_file

        Create folder
        """
        pass

    def test_fs_replace_in_files(self) -> None:
        """Test case for fs_replace_in_files

        Repleace text/pattern in files
        """
        pass

    def test_fs_search_files(self) -> None:
        """Test case for fs_search_files

        Search for files
        """
        pass

    def test_fs_set_file_permissions(self) -> None:
        """Test case for fs_set_file_permissions

        Set file owner/group/permissions
        """
        pass

    def test_fs_upload_file(self) -> None:
        """Test case for fs_upload_file

        Upload file
        """
        pass

    def test_get_project_dir(self) -> None:
        """Test case for get_project_dir

        Get project dir
        """
        pass

    def test_git_add_files(self) -> None:
        """Test case for git_add_files

        Add files
        """
        pass

    def test_git_branch_list(self) -> None:
        """Test case for git_branch_list

        Get branch list
        """
        pass

    def test_git_clone_repository(self) -> None:
        """Test case for git_clone_repository

        Clone git repository
        """
        pass

    def test_git_commit_changes(self) -> None:
        """Test case for git_commit_changes

        Commit changes
        """
        pass

    def test_git_commit_history(self) -> None:
        """Test case for git_commit_history

        Get commit history
        """
        pass

    def test_git_create_branch(self) -> None:
        """Test case for git_create_branch

        Create branch
        """
        pass

    def test_git_git_status(self) -> None:
        """Test case for git_git_status

        Get git status
        """
        pass

    def test_git_pull_changes(self) -> None:
        """Test case for git_pull_changes

        Pull changes
        """
        pass

    def test_git_push_changes(self) -> None:
        """Test case for git_push_changes

        Push changes
        """
        pass

    def test_lsp_completions(self) -> None:
        """Test case for lsp_completions

        Get Lsp Completions
        """
        pass

    def test_lsp_did_close(self) -> None:
        """Test case for lsp_did_close

        Call Lsp DidClose
        """
        pass

    def test_lsp_did_open(self) -> None:
        """Test case for lsp_did_open

        Call Lsp DidOpen
        """
        pass

    def test_lsp_document_symbols(self) -> None:
        """Test case for lsp_document_symbols

        Call Lsp DocumentSymbols
        """
        pass

    def test_lsp_start(self) -> None:
        """Test case for lsp_start

        Start Lsp server
        """
        pass

    def test_lsp_stop(self) -> None:
        """Test case for lsp_stop

        Stop Lsp server
        """
        pass

    def test_lsp_workspace_symbols(self) -> None:
        """Test case for lsp_workspace_symbols

        Call Lsp WorkspaceSymbols
        """
        pass

    def test_process_execute_command(self) -> None:
        """Test case for process_execute_command

        Execute command
        """
        pass


if __name__ == '__main__':
    unittest.main()
