/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentToolboxLspCompletionContext
 */
export interface AgentToolboxLspCompletionContext {
    /**
     * 
     * @type {string}
     * @memberof AgentToolboxLspCompletionContext
     */
    triggerCharacter?: string;
    /**
     * 
     * @type {number}
     * @memberof AgentToolboxLspCompletionContext
     */
    triggerKind?: number;
}

/**
 * Check if a given object implements the AgentToolboxLspCompletionContext interface.
 */
export function instanceOfAgentToolboxLspCompletionContext(value: object): value is AgentToolboxLspCompletionContext {
    return true;
}

export function AgentToolboxLspCompletionContextFromJSON(json: any): AgentToolboxLspCompletionContext {
    return AgentToolboxLspCompletionContextFromJSONTyped(json, false);
}

export function AgentToolboxLspCompletionContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentToolboxLspCompletionContext {
    if (json == null) {
        return json;
    }
    return {
        
        'triggerCharacter': json['triggerCharacter'] == null ? undefined : json['triggerCharacter'],
        'triggerKind': json['triggerKind'] == null ? undefined : json['triggerKind'],
    };
}

export function AgentToolboxLspCompletionContextToJSON(json: any): AgentToolboxLspCompletionContext {
    return AgentToolboxLspCompletionContextToJSONTyped(json, false);
}

export function AgentToolboxLspCompletionContextToJSONTyped(value?: AgentToolboxLspCompletionContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'triggerCharacter': value['triggerCharacter'],
        'triggerKind': value['triggerKind'],
    };
}

