/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CachedBuild } from './CachedBuild'
import {
  CachedBuildFromJSON,
  CachedBuildFromJSONTyped,
  CachedBuildToJSON,
  CachedBuildToJSONTyped,
} from './CachedBuild'
import type { DevcontainerConfig } from './DevcontainerConfig'
import {
  DevcontainerConfigFromJSON,
  DevcontainerConfigFromJSONTyped,
  DevcontainerConfigToJSON,
  DevcontainerConfigToJSONTyped,
} from './DevcontainerConfig'

/**
 *
 * @export
 * @interface BuildConfig
 */
export interface BuildConfig {
  /**
   *
   * @type {CachedBuild}
   * @memberof BuildConfig
   */
  cachedBuild?: CachedBuild
  /**
   *
   * @type {DevcontainerConfig}
   * @memberof BuildConfig
   */
  devcontainer?: DevcontainerConfig
}

/**
 * Check if a given object implements the BuildConfig interface.
 */
export function instanceOfBuildConfig(value: object): value is BuildConfig {
  return true
}

export function BuildConfigFromJSON(json: any): BuildConfig {
  return BuildConfigFromJSONTyped(json, false)
}

export function BuildConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BuildConfig {
  if (json == null) {
    return json
  }
  return {
    cachedBuild:
      json['cachedBuild'] == null
        ? undefined
        : CachedBuildFromJSON(json['cachedBuild']),
    devcontainer:
      json['devcontainer'] == null
        ? undefined
        : DevcontainerConfigFromJSON(json['devcontainer']),
  }
}

export function BuildConfigToJSON(json: any): BuildConfig {
  return BuildConfigToJSONTyped(json, false)
}

export function BuildConfigToJSONTyped(
  value?: BuildConfig | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    cachedBuild: CachedBuildToJSON(value['cachedBuild']),
    devcontainer: DevcontainerConfigToJSON(value['devcontainer']),
  }
}
