/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateBuildDTO
 */
export interface CreateBuildDTO {
  /**
   *
   * @type {string}
   * @memberof CreateBuildDTO
   */
  branch: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof CreateBuildDTO
   */
  envVars: { [key: string]: string }
  /**
   *
   * @type {string}
   * @memberof CreateBuildDTO
   */
  prebuildId?: string
  /**
   *
   * @type {string}
   * @memberof CreateBuildDTO
   */
  projectConfigName: string
}

/**
 * Check if a given object implements the CreateBuildDTO interface.
 */
export function instanceOfCreateBuildDTO(
  value: object,
): value is CreateBuildDTO {
  if (!('branch' in value) || value['branch'] === undefined) return false
  if (!('envVars' in value) || value['envVars'] === undefined) return false
  if (
    !('projectConfigName' in value) ||
    value['projectConfigName'] === undefined
  )
    return false
  return true
}

export function CreateBuildDTOFromJSON(json: any): CreateBuildDTO {
  return CreateBuildDTOFromJSONTyped(json, false)
}

export function CreateBuildDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateBuildDTO {
  if (json == null) {
    return json
  }
  return {
    branch: json['branch'],
    envVars: json['envVars'],
    prebuildId: json['prebuildId'] == null ? undefined : json['prebuildId'],
    projectConfigName: json['projectConfigName'],
  }
}

export function CreateBuildDTOToJSON(json: any): CreateBuildDTO {
  return CreateBuildDTOToJSONTyped(json, false)
}

export function CreateBuildDTOToJSONTyped(
  value?: CreateBuildDTO | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    branch: value['branch'],
    envVars: value['envVars'],
    prebuildId: value['prebuildId'],
    projectConfigName: value['projectConfigName'],
  }
}
