/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GitCommitResponse
 */
export interface GitCommitResponse {
  /**
   *
   * @type {string}
   * @memberof GitCommitResponse
   */
  hash: string
}

/**
 * Check if a given object implements the GitCommitResponse interface.
 */
export function instanceOfGitCommitResponse(
  value: object,
): value is GitCommitResponse {
  if (!('hash' in value) || value['hash'] === undefined) return false
  return true
}

export function GitCommitResponseFromJSON(json: any): GitCommitResponse {
  return GitCommitResponseFromJSONTyped(json, false)
}

export function GitCommitResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GitCommitResponse {
  if (json == null) {
    return json
  }
  return {
    hash: json['hash'],
  }
}

export function GitCommitResponseToJSON(json: any): GitCommitResponse {
  return GitCommitResponseToJSONTyped(json, false)
}

export function GitCommitResponseToJSONTyped(
  value?: GitCommitResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    hash: value['hash'],
  }
}
