/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InstallProviderRequest
 */
export interface InstallProviderRequest {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof InstallProviderRequest
   */
  downloadUrls: { [key: string]: string }
  /**
   *
   * @type {string}
   * @memberof InstallProviderRequest
   */
  name: string
}

/**
 * Check if a given object implements the InstallProviderRequest interface.
 */
export function instanceOfInstallProviderRequest(
  value: object,
): value is InstallProviderRequest {
  if (!('downloadUrls' in value) || value['downloadUrls'] === undefined)
    return false
  if (!('name' in value) || value['name'] === undefined) return false
  return true
}

export function InstallProviderRequestFromJSON(
  json: any,
): InstallProviderRequest {
  return InstallProviderRequestFromJSONTyped(json, false)
}

export function InstallProviderRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InstallProviderRequest {
  if (json == null) {
    return json
  }
  return {
    downloadUrls: json['downloadUrls'],
    name: json['name'],
  }
}

export function InstallProviderRequestToJSON(
  json: any,
): InstallProviderRequest {
  return InstallProviderRequestToJSONTyped(json, false)
}

export function InstallProviderRequestToJSONTyped(
  value?: InstallProviderRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    downloadUrls: value['downloadUrls'],
    name: value['name'],
  }
}
