/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Match
 */
export interface Match {
  /**
   *
   * @type {string}
   * @memberof Match
   */
  content: string
  /**
   *
   * @type {string}
   * @memberof Match
   */
  file: string
  /**
   *
   * @type {number}
   * @memberof Match
   */
  line: number
}

/**
 * Check if a given object implements the Match interface.
 */
export function instanceOfMatch(value: object): value is Match {
  if (!('content' in value) || value['content'] === undefined) return false
  if (!('file' in value) || value['file'] === undefined) return false
  if (!('line' in value) || value['line'] === undefined) return false
  return true
}

export function MatchFromJSON(json: any): Match {
  return MatchFromJSONTyped(json, false)
}

export function MatchFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Match {
  if (json == null) {
    return json
  }
  return {
    content: json['content'],
    file: json['file'],
    line: json['line'],
  }
}

export function MatchToJSON(json: any): Match {
  return MatchToJSONTyped(json, false)
}

export function MatchToJSONTyped(
  value?: Match | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    content: value['content'],
    file: value['file'],
    line: value['line'],
  }
}
