/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface NetworkKey
 */
export interface NetworkKey {
  /**
   *
   * @type {string}
   * @memberof NetworkKey
   */
  key: string
}

/**
 * Check if a given object implements the NetworkKey interface.
 */
export function instanceOfNetworkKey(value: object): value is NetworkKey {
  if (!('key' in value) || value['key'] === undefined) return false
  return true
}

export function NetworkKeyFromJSON(json: any): NetworkKey {
  return NetworkKeyFromJSONTyped(json, false)
}

export function NetworkKeyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NetworkKey {
  if (json == null) {
    return json
  }
  return {
    key: json['key'],
  }
}

export function NetworkKeyToJSON(json: any): NetworkKey {
  return NetworkKeyToJSONTyped(json, false)
}

export function NetworkKeyToJSONTyped(
  value?: NetworkKey | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    key: value['key'],
  }
}
