/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PrebuildConfig
 */
export interface PrebuildConfig {
  /**
   *
   * @type {string}
   * @memberof PrebuildConfig
   */
  branch: string
  /**
   *
   * @type {number}
   * @memberof PrebuildConfig
   */
  commitInterval: number
  /**
   *
   * @type {string}
   * @memberof PrebuildConfig
   */
  id: string
  /**
   *
   * @type {number}
   * @memberof PrebuildConfig
   */
  retention: number
  /**
   *
   * @type {Array<string>}
   * @memberof PrebuildConfig
   */
  triggerFiles: Array<string>
}

/**
 * Check if a given object implements the PrebuildConfig interface.
 */
export function instanceOfPrebuildConfig(
  value: object,
): value is PrebuildConfig {
  if (!('branch' in value) || value['branch'] === undefined) return false
  if (!('commitInterval' in value) || value['commitInterval'] === undefined)
    return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('retention' in value) || value['retention'] === undefined) return false
  if (!('triggerFiles' in value) || value['triggerFiles'] === undefined)
    return false
  return true
}

export function PrebuildConfigFromJSON(json: any): PrebuildConfig {
  return PrebuildConfigFromJSONTyped(json, false)
}

export function PrebuildConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrebuildConfig {
  if (json == null) {
    return json
  }
  return {
    branch: json['branch'],
    commitInterval: json['commitInterval'],
    id: json['id'],
    retention: json['retention'],
    triggerFiles: json['triggerFiles'],
  }
}

export function PrebuildConfigToJSON(json: any): PrebuildConfig {
  return PrebuildConfigToJSONTyped(json, false)
}

export function PrebuildConfigToJSONTyped(
  value?: PrebuildConfig | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    branch: value['branch'],
    commitInterval: value['commitInterval'],
    id: value['id'],
    retention: value['retention'],
    triggerFiles: value['triggerFiles'],
  }
}
