/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ReplaceResult
 */
export interface ReplaceResult {
  /**
   *
   * @type {string}
   * @memberof ReplaceResult
   */
  error?: string
  /**
   *
   * @type {string}
   * @memberof ReplaceResult
   */
  file?: string
  /**
   *
   * @type {boolean}
   * @memberof ReplaceResult
   */
  success?: boolean
}

/**
 * Check if a given object implements the ReplaceResult interface.
 */
export function instanceOfReplaceResult(value: object): value is ReplaceResult {
  return true
}

export function ReplaceResultFromJSON(json: any): ReplaceResult {
  return ReplaceResultFromJSONTyped(json, false)
}

export function ReplaceResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReplaceResult {
  if (json == null) {
    return json
  }
  return {
    error: json['error'] == null ? undefined : json['error'],
    file: json['file'] == null ? undefined : json['file'],
    success: json['success'] == null ? undefined : json['success'],
  }
}

export function ReplaceResultToJSON(json: any): ReplaceResult {
  return ReplaceResultToJSONTyped(json, false)
}

export function ReplaceResultToJSONTyped(
  value?: ReplaceResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    error: value['error'],
    file: value['file'],
    success: value['success'],
  }
}
