/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { SigningMethod } from './SigningMethod'
import {
  SigningMethodFromJSON,
  SigningMethodFromJSONTyped,
  SigningMethodToJSON,
  SigningMethodToJSONTyped,
} from './SigningMethod'

/**
 *
 * @export
 * @interface SetGitProviderConfig
 */
export interface SetGitProviderConfig {
  /**
   *
   * @type {string}
   * @memberof SetGitProviderConfig
   */
  alias?: string
  /**
   *
   * @type {string}
   * @memberof SetGitProviderConfig
   */
  baseApiUrl?: string
  /**
   *
   * @type {string}
   * @memberof SetGitProviderConfig
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof SetGitProviderConfig
   */
  providerId: string
  /**
   *
   * @type {string}
   * @memberof SetGitProviderConfig
   */
  signingKey?: string
  /**
   *
   * @type {SigningMethod}
   * @memberof SetGitProviderConfig
   */
  signingMethod?: SigningMethod
  /**
   *
   * @type {string}
   * @memberof SetGitProviderConfig
   */
  token: string
  /**
   *
   * @type {string}
   * @memberof SetGitProviderConfig
   */
  username?: string
}

/**
 * Check if a given object implements the SetGitProviderConfig interface.
 */
export function instanceOfSetGitProviderConfig(
  value: object,
): value is SetGitProviderConfig {
  if (!('providerId' in value) || value['providerId'] === undefined)
    return false
  if (!('token' in value) || value['token'] === undefined) return false
  return true
}

export function SetGitProviderConfigFromJSON(json: any): SetGitProviderConfig {
  return SetGitProviderConfigFromJSONTyped(json, false)
}

export function SetGitProviderConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SetGitProviderConfig {
  if (json == null) {
    return json
  }
  return {
    alias: json['alias'] == null ? undefined : json['alias'],
    baseApiUrl: json['baseApiUrl'] == null ? undefined : json['baseApiUrl'],
    id: json['id'] == null ? undefined : json['id'],
    providerId: json['providerId'],
    signingKey: json['signingKey'] == null ? undefined : json['signingKey'],
    signingMethod:
      json['signingMethod'] == null
        ? undefined
        : SigningMethodFromJSON(json['signingMethod']),
    token: json['token'],
    username: json['username'] == null ? undefined : json['username'],
  }
}

export function SetGitProviderConfigToJSON(json: any): SetGitProviderConfig {
  return SetGitProviderConfigToJSONTyped(json, false)
}

export function SetGitProviderConfigToJSONTyped(
  value?: SetGitProviderConfig | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    alias: value['alias'],
    baseApiUrl: value['baseApiUrl'],
    id: value['id'],
    providerId: value['providerId'],
    signingKey: value['signingKey'],
    signingMethod: SigningMethodToJSON(value['signingMethod']),
    token: value['token'],
    username: value['username'],
  }
}
