/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextDocumentIdentifier
 */
export interface TextDocumentIdentifier {
    /**
     * 
     * @type {string}
     * @memberof TextDocumentIdentifier
     */
    uri?: string;
}

/**
 * Check if a given object implements the TextDocumentIdentifier interface.
 */
export function instanceOfTextDocumentIdentifier(value: object): value is TextDocumentIdentifier {
    return true;
}

export function TextDocumentIdentifierFromJSON(json: any): TextDocumentIdentifier {
    return TextDocumentIdentifierFromJSONTyped(json, false);
}

export function TextDocumentIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextDocumentIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'uri': json['uri'] == null ? undefined : json['uri'],
    };
}

export function TextDocumentIdentifierToJSON(json: any): TextDocumentIdentifier {
    return TextDocumentIdentifierToJSONTyped(json, false);
}

export function TextDocumentIdentifierToJSONTyped(value?: TextDocumentIdentifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uri': value['uri'],
    };
}

