# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from apiclient.models.create_project_config_dto import CreateProjectConfigDTO

class TestCreateProjectConfigDTO(unittest.TestCase):
    """CreateProjectConfigDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProjectConfigDTO:
        """Test CreateProjectConfigDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProjectConfigDTO`
        """
        model = CreateProjectConfigDTO()
        if include_optional:
            return CreateProjectConfigDTO(
                build_config = apiclient.models.build_config.BuildConfig(
                    cached_build = apiclient.models.cached_build.CachedBuild(
                        image = '', 
                        user = '', ), 
                    devcontainer = apiclient.models.devcontainer_config.DevcontainerConfig(
                        file_path = '', ), ),
                env_vars = {
                    'key' : ''
                    },
                git_provider_config_id = '',
                image = '',
                name = '',
                repository_url = '',
                user = ''
            )
        else:
            return CreateProjectConfigDTO(
                env_vars = {
                    'key' : ''
                    },
                name = '',
                repository_url = '',
        )
        """

    def testCreateProjectConfigDTO(self):
        """Test CreateProjectConfigDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
