# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from apiclient.models.signing_method import SigningMethod

class TestSigningMethod(unittest.TestCase):
    """SigningMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSigningMethod(self):
        """Test SigningMethod"""
        # inst = SigningMethod()

if __name__ == '__main__':
    unittest.main()
