# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from apiclient.api.sample_api import SampleApi


class TestSampleApi(unittest.TestCase):
    """SampleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SampleApi()

    def tearDown(self) -> None:
        pass

    def test_list_samples(self) -> None:
        """Test case for list_samples

        List samples
        """
        pass


if __name__ == '__main__':
    unittest.main()
