# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from apiclient.models.set_git_provider_config import SetGitProviderConfig

class TestSetGitProviderConfig(unittest.TestCase):
    """SetGitProviderConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetGitProviderConfig:
        """Test SetGitProviderConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetGitProviderConfig`
        """
        model = SetGitProviderConfig()
        if include_optional:
            return SetGitProviderConfig(
                alias = '',
                base_api_url = '',
                id = '',
                provider_id = '',
                signing_key = '',
                signing_method = 'ssh',
                token = '',
                username = ''
            )
        else:
            return SetGitProviderConfig(
                provider_id = '',
                token = '',
        )
        """

    def testSetGitProviderConfig(self):
        """Test SetGitProviderConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
