/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CloneTarget = {
  CloneTargetBranch: 'branch',
  CloneTargetCommit: 'commit',
} as const
export type CloneTarget = (typeof CloneTarget)[keyof typeof CloneTarget]

export function instanceOfCloneTarget(value: any): boolean {
  for (const key in CloneTarget) {
    if (Object.prototype.hasOwnProperty.call(CloneTarget, key)) {
      if (CloneTarget[key as keyof typeof CloneTarget] === value) {
        return true
      }
    }
  }
  return false
}

export function CloneTargetFromJSON(json: any): CloneTarget {
  return CloneTargetFromJSONTyped(json, false)
}

export function CloneTargetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CloneTarget {
  return json as CloneTarget
}

export function CloneTargetToJSON(value?: CloneTarget | null): any {
  return value as any
}

export function CloneTargetToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): CloneTarget {
  return value as CloneTarget
}
