/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CompletionContext
 */
export interface CompletionContext {
  /**
   *
   * @type {string}
   * @memberof CompletionContext
   */
  triggerCharacter?: string
  /**
   *
   * @type {number}
   * @memberof CompletionContext
   */
  triggerKind: number
}

/**
 * Check if a given object implements the CompletionContext interface.
 */
export function instanceOfCompletionContext(
  value: object,
): value is CompletionContext {
  if (!('triggerKind' in value) || value['triggerKind'] === undefined)
    return false
  return true
}

export function CompletionContextFromJSON(json: any): CompletionContext {
  return CompletionContextFromJSONTyped(json, false)
}

export function CompletionContextFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompletionContext {
  if (json == null) {
    return json
  }
  return {
    triggerCharacter:
      json['triggerCharacter'] == null ? undefined : json['triggerCharacter'],
    triggerKind: json['triggerKind'],
  }
}

export function CompletionContextToJSON(json: any): CompletionContext {
  return CompletionContextToJSONTyped(json, false)
}

export function CompletionContextToJSONTyped(
  value?: CompletionContext | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    triggerCharacter: value['triggerCharacter'],
    triggerKind: value['triggerKind'],
  }
}
