/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LspPosition
 */
export interface LspPosition {
  /**
   *
   * @type {number}
   * @memberof LspPosition
   */
  character: number
  /**
   *
   * @type {number}
   * @memberof LspPosition
   */
  line: number
}

/**
 * Check if a given object implements the LspPosition interface.
 */
export function instanceOfLspPosition(value: object): value is LspPosition {
  if (!('character' in value) || value['character'] === undefined) return false
  if (!('line' in value) || value['line'] === undefined) return false
  return true
}

export function LspPositionFromJSON(json: any): LspPosition {
  return LspPositionFromJSONTyped(json, false)
}

export function LspPositionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LspPosition {
  if (json == null) {
    return json
  }
  return {
    character: json['character'],
    line: json['line'],
  }
}

export function LspPositionToJSON(json: any): LspPosition {
  return LspPositionToJSONTyped(json, false)
}

export function LspPositionToJSONTyped(
  value?: LspPosition | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    character: value['character'],
    line: value['line'],
  }
}
