/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ProfileData
 */
export interface ProfileData {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ProfileData
   */
  envVars: { [key: string]: string }
}

/**
 * Check if a given object implements the ProfileData interface.
 */
export function instanceOfProfileData(value: object): value is ProfileData {
  if (!('envVars' in value) || value['envVars'] === undefined) return false
  return true
}

export function ProfileDataFromJSON(json: any): ProfileData {
  return ProfileDataFromJSONTyped(json, false)
}

export function ProfileDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProfileData {
  if (json == null) {
    return json
  }
  return {
    envVars: json['envVars'],
  }
}

export function ProfileDataToJSON(json: any): ProfileData {
  return ProfileDataToJSONTyped(json, false)
}

export function ProfileDataToJSONTyped(
  value?: ProfileData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    envVars: value['envVars'],
  }
}
