/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ProjectDirResponse
 */
export interface ProjectDirResponse {
  /**
   *
   * @type {string}
   * @memberof ProjectDirResponse
   */
  dir?: string
}

/**
 * Check if a given object implements the ProjectDirResponse interface.
 */
export function instanceOfProjectDirResponse(
  value: object,
): value is ProjectDirResponse {
  return true
}

export function ProjectDirResponseFromJSON(json: any): ProjectDirResponse {
  return ProjectDirResponseFromJSONTyped(json, false)
}

export function ProjectDirResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectDirResponse {
  if (json == null) {
    return json
  }
  return {
    dir: json['dir'] == null ? undefined : json['dir'],
  }
}

export function ProjectDirResponseToJSON(json: any): ProjectDirResponse {
  return ProjectDirResponseToJSONTyped(json, false)
}

export function ProjectDirResponseToJSONTyped(
  value?: ProjectDirResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    dir: value['dir'],
  }
}
