/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Provider
 */
export interface Provider {
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  label?: string
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  version: string
}

/**
 * Check if a given object implements the Provider interface.
 */
export function instanceOfProvider(value: object): value is Provider {
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('version' in value) || value['version'] === undefined) return false
  return true
}

export function ProviderFromJSON(json: any): Provider {
  return ProviderFromJSONTyped(json, false)
}

export function ProviderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Provider {
  if (json == null) {
    return json
  }
  return {
    label: json['label'] == null ? undefined : json['label'],
    name: json['name'],
    version: json['version'],
  }
}

export function ProviderToJSON(json: any): Provider {
  return ProviderToJSONTyped(json, false)
}

export function ProviderToJSONTyped(
  value?: Provider | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    label: value['label'],
    name: value['name'],
    version: value['version'],
  }
}
