/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SearchFilesResponse
 */
export interface SearchFilesResponse {
  /**
   *
   * @type {Array<string>}
   * @memberof SearchFilesResponse
   */
  files: Array<string>
}

/**
 * Check if a given object implements the SearchFilesResponse interface.
 */
export function instanceOfSearchFilesResponse(
  value: object,
): value is SearchFilesResponse {
  if (!('files' in value) || value['files'] === undefined) return false
  return true
}

export function SearchFilesResponseFromJSON(json: any): SearchFilesResponse {
  return SearchFilesResponseFromJSONTyped(json, false)
}

export function SearchFilesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SearchFilesResponse {
  if (json == null) {
    return json
  }
  return {
    files: json['files'],
  }
}

export function SearchFilesResponseToJSON(json: any): SearchFilesResponse {
  return SearchFilesResponseToJSONTyped(json, false)
}

export function SearchFilesResponseToJSONTyped(
  value?: SearchFilesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    files: value['files'],
  }
}
