/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Server API
 * Daytona Server API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GitStatus } from './GitStatus'
import {
  GitStatusFromJSON,
  GitStatusFromJSONTyped,
  GitStatusToJSON,
  GitStatusToJSONTyped,
} from './GitStatus'

/**
 *
 * @export
 * @interface SetProjectState
 */
export interface SetProjectState {
  /**
   *
   * @type {GitStatus}
   * @memberof SetProjectState
   */
  gitStatus?: GitStatus
  /**
   *
   * @type {number}
   * @memberof SetProjectState
   */
  uptime: number
}

/**
 * Check if a given object implements the SetProjectState interface.
 */
export function instanceOfSetProjectState(
  value: object,
): value is SetProjectState {
  if (!('uptime' in value) || value['uptime'] === undefined) return false
  return true
}

export function SetProjectStateFromJSON(json: any): SetProjectState {
  return SetProjectStateFromJSONTyped(json, false)
}

export function SetProjectStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SetProjectState {
  if (json == null) {
    return json
  }
  return {
    gitStatus:
      json['gitStatus'] == null
        ? undefined
        : GitStatusFromJSON(json['gitStatus']),
    uptime: json['uptime'],
  }
}

export function SetProjectStateToJSON(json: any): SetProjectState {
  return SetProjectStateToJSONTyped(json, false)
}

export function SetProjectStateToJSONTyped(
  value?: SetProjectState | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    gitStatus: GitStatusToJSON(value['gitStatus']),
    uptime: value['uptime'],
  }
}
