# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytonasdk.models.clone_target import CloneTarget

class TestCloneTarget(unittest.TestCase):
    """CloneTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloneTarget(self):
        """Test CloneTarget"""
        # inst = CloneTarget()

if __name__ == '__main__':
    unittest.main()
