# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytonasdk.models.provider_provider_info import ProviderProviderInfo

class TestProviderProviderInfo(unittest.TestCase):
    """ProviderProviderInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderProviderInfo:
        """Test ProviderProviderInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderProviderInfo`
        """
        model = ProviderProviderInfo()
        if include_optional:
            return ProviderProviderInfo(
                label = '',
                name = '',
                version = ''
            )
        else:
            return ProviderProviderInfo(
                name = '',
                version = '',
        )
        """

    def testProviderProviderInfo(self):
        """Test ProviderProviderInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
