# coding: utf-8

"""
    Daytona Server API

    Daytona Server API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytonasdk.models.file_info import FileInfo

class TestFileInfo(unittest.TestCase):
    """FileInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileInfo:
        """Test FileInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileInfo`
        """
        model = FileInfo()
        if include_optional:
            return FileInfo(
                group = '',
                is_dir = True,
                mod_time = '',
                mode = '',
                name = '',
                owner = '',
                permissions = '',
                size = 56
            )
        else:
            return FileInfo(
                group = '',
                is_dir = True,
                mod_time = '',
                mode = '',
                name = '',
                owner = '',
                permissions = '',
                size = 56,
        )
        """

    def testFileInfo(self):
        """Test FileInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
